# Generated by Django 4.2.25 on 2025-12-28 14:05

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('company', 'Company'), ('jobseeker', 'Job Seeker')], default='jobseeker', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Employee name or identifier', max_length=255)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('employee_id', models.CharField(blank=True, help_text='Internal employee ID', max_length=100, null=True)),
                ('leetcode_username', models.CharField(max_length=100)),
                ('leetcode_url', models.URLField()),
                ('team', models.CharField(blank=True, help_text='Team or department name', max_length=100, null=True)),
                ('role', models.CharField(blank=True, help_text='Job role/title', max_length=100, null=True)),
                ('auto_sync_enabled', models.BooleanField(default=False, help_text='Enable automatic periodic syncing')),
                ('sync_frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='weekly', help_text="How often to automatically sync this employee's profile", max_length=20)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('next_sync', models.DateTimeField(blank=True, help_text='Next scheduled sync time', null=True)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about the employee', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this employee is currently being tracked')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CodingProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('leetcode', 'LeetCode'), ('hackerrank', 'HackerRank')], max_length=20)),
                ('username', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, null=True)),
                ('stats', models.JSONField(blank=True, default=dict)),
                ('analysis', models.JSONField(blank=True, default=dict)),
                ('last_synced', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coding_profiles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['platform'],
            },
        ),
        migrations.CreateModel(
            name='LeetCodeAnalysisHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_identifier', models.CharField(help_text='Username or CSV name', max_length=255)),
                ('leetcode_username', models.CharField(blank=True, max_length=100, null=True)),
                ('leetcode_url', models.URLField()),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('total_solved', models.IntegerField(default=0)),
                ('easy_solved', models.IntegerField(default=0)),
                ('medium_solved', models.IntegerField(default=0)),
                ('hard_solved', models.IntegerField(default=0)),
                ('problem_solving_score', models.IntegerField(default=0, help_text='Score out of 100')),
                ('ranking', models.IntegerField(default=0)),
                ('acceptance_rate', models.FloatField(default=0.0)),
                ('current_streak', models.IntegerField(default=0)),
                ('max_streak', models.IntegerField(default=0)),
                ('activity_status', models.CharField(blank=True, max_length=20, null=True)),
                ('full_stats', models.JSONField(default=dict, help_text='Complete stats from LeetCode API')),
                ('analysis_data', models.JSONField(default=dict, help_text='AI analysis results')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leetcode_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'LeetCode Analysis Histories',
                'ordering': ['-analyzed_at'],
                'indexes': [models.Index(fields=['company', 'employee_identifier', '-analyzed_at'], name='api_leetcod_company_f6e9ff_idx'), models.Index(fields=['company', '-analyzed_at'], name='api_leetcod_company_40a6b9_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmployeeGoal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('metric_type', models.CharField(choices=[('total_solved', 'Total Problems Solved'), ('easy_solved', 'Easy Problems Solved'), ('medium_solved', 'Medium Problems Solved'), ('hard_solved', 'Hard Problems Solved'), ('problem_solving_score', 'Problem Solving Score'), ('acceptance_rate', 'Acceptance Rate'), ('current_streak', 'Current Streak'), ('ranking', 'Ranking (lower is better)')], max_length=50)),
                ('target_value', models.FloatField(help_text='Target value to achieve')),
                ('current_value', models.FloatField(default=0, help_text='Current value (updated on sync)')),
                ('start_value', models.FloatField(default=0, help_text='Value when goal was set')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('target_date', models.DateTimeField(help_text='Deadline for achieving the goal')),
                ('achieved_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_goals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goals', to='api.employee')),
            ],
            options={
                'ordering': ['-target_date', '-created_at'],
                'indexes': [models.Index(fields=['employee', 'is_active'], name='api_employe_employe_9f3661_idx'), models.Index(fields=['company', 'is_active', '-target_date'], name='api_employe_company_92a984_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'is_active'], name='api_employe_company_107ac1_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', 'team'], name='api_employe_company_a2e8d8_idx'),
        ),
        migrations.AddIndex(
            model_name='employee',
            index=models.Index(fields=['company', '-last_synced'], name='api_employe_company_b01927_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together={('company', 'leetcode_username')},
        ),
        migrations.AlterUniqueTogether(
            name='codingprofile',
            unique_together={('user', 'platform')},
        ),
    ]
